### ISSUE TITLE
Support for torch 1.5 and above

### ISSUE THREAD

**Issue by MrCrHaM** [fab-jul/torchac#1]
Compiling failed for torch 1.5.1.
To sovle it,  replace AT_CHECK with TORCH_CHECK. 
Solution is found [here](https://github.com/open-mmlab/mmdetection/issues/2513#issue-605212826).

**Comment by fab-jul** [comment]
Hi I just updated the code today. This repo is now separate from L3C, if you want to use it in research. No compilation required anymore, as it's now done on the fly with ninja.

**Comment by MrCrHaM** [comment]
Thanks so much for the update. It really helps a lot. 😊
