### ISSUE TITLE
How to use torchac in an autoregressive compression manner?

### ISSUE THREAD

**Issue by JPEG2021** [fab-jul/torchac#2]
Thanks for the nice work and sharing!
It seems that the library requires the shapes of `output_cdf` and `sym` to be `B, C, H, W, Lp` and `B, C, H, W` respectively.
However, when using the autoregressive context probability model, I have to compress each symbol one by one.
Is there any way to use the library in the autoregressive manner?
Thanks.

**Comment by fab-jul** [comment]
Hi, it's not made for this use case but you can do it by calling decode multiple times with shapes set to (1, 1, 1, 1, Lp) for output_cdf. It will probably be slow :)

To support fully autoregressive models within the C++ code, we would need to add a way to call into the CNN that predicts your CDF.

**Comment by JPEG2021** [comment]
Thank you for the answer!

**Comment by zb12138** [comment]
You can see this implementation https://github.com/zb12138/NumpyAc
